[build]
target-dir = "target"
rustflags = ["-C", "target-cpu=native", "-C", "link-arg=-fuse-ld=lld"]

[target.'cfg(target_os = "windows")']
rustflags = ["-C", "target-feature=+crt-static"]

[profile.release]
lto = "thin"
codegen-units = 1
panic = "abort"
strip = true
opt-level = 3
incremental = false

[profile.dev]
opt-level = 0
debug = true
split-debuginfo = "unpacked"
debug-assertions = true
overflow-checks = true
lto = false
panic = "unwind"
incremental = true
codegen-units = 256
rpath = false 