# SMART APE NEURAL SWARM - ALERTMANAGER CONFIGURATION
# ================================================

global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/REPLACE/WITH/WEBHOOK'
  telegram_api_url: 'https://api.telegram.org'
  telegram_bot_token: 'REPLACE_WITH_BOT_TOKEN'
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@example.com'
  smtp_auth_username: 'alerts@example.com'
  smtp_auth_password: 'REPLACE_WITH_APP_PASSWORD'
  smtp_require_tls: true

templates:
  - '/etc/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname', 'category', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'team-trading'
  routes:
    - match:
        severity: critical
      receiver: 'team-trading-critical'
      repeat_interval: 1h
      continue: true

    - match:
        category: security
      receiver: 'team-security'
      group_wait: 10s
      continue: true

    - match:
        category: trading
      receiver: 'team-trading'
      continue: true

    - match:
        category: infrastructure
      receiver: 'team-devops'
      continue: true

    - match:
        severity: warning
      receiver: 'team-trading-warnings'
      continue: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'category']

receivers:
  - name: 'team-trading-critical'
    slack_configs:
      - channel: '#trading-alerts-critical'
        send_resolved: true
        icon_url: 'https://example.com/icons/critical.png'
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
        actions:
          - type: button
            text: 'View Dashboard'
            url: '{{ .CommonAnnotations.dashboard_url }}'
    telegram_configs:
      - chat_id: -1001234567890
        parse_mode: 'HTML'
        message: '{{ template "telegram.message" . }}'
    email_configs:
      - to: 'trading-team@example.com'
        send_resolved: true
        headers:
          subject: '{{ template "email.subject" . }}'
        html: '{{ template "email.html" . }}'

  - name: 'team-trading'
    slack_configs:
      - channel: '#trading-alerts'
        send_resolved: true
        icon_url: 'https://example.com/icons/warning.png'
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
    email_configs:
      - to: 'trading-team@example.com'
        send_resolved: true

  - name: 'team-security'
    slack_configs:
      - channel: '#security-alerts'
        send_resolved: true
        icon_url: 'https://example.com/icons/security.png'
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
    telegram_configs:
      - chat_id: -1001234567891
        parse_mode: 'HTML'
        message: '{{ template "telegram.message" . }}'
    email_configs:
      - to: 'security-team@example.com'
        send_resolved: true

  - name: 'team-devops'
    slack_configs:
      - channel: '#devops-alerts'
        send_resolved: true
        icon_url: 'https://example.com/icons/infrastructure.png'
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
    email_configs:
      - to: 'devops-team@example.com'
        send_resolved: true

  - name: 'team-trading-warnings'
    slack_configs:
      - channel: '#trading-alerts-warnings'
        send_resolved: true
        icon_url: 'https://example.com/icons/warning.png'
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}' 