# SMART APE NEURAL SWARM - ALERTMANAGER CONFIGURATION
# ================================================

global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@yourdomain.com'
  smtp_auth_username: 'alerts@yourdomain.com'
  smtp_auth_password: 'your_app_password_here'
  smtp_require_tls: true

templates:
  - '/etc/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
    continue: true
  - match:
      severity: warning
    receiver: 'warning-alerts'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'

- name: 'critical-alerts'
  email_configs:
  - to: 'admin@yourdomain.com'
    send_resolved: true
    headers:
      subject: '🚨 CRITICAL ALERT: {{ .GroupLabels.alertname }}'
    html: |
      <h2>Critical Alert</h2>
      <p><strong>Alert:</strong> {{ .GroupLabels.alertname }}</p>
      <p><strong>Service:</strong> {{ .GroupLabels.service }}</p>
      <p><strong>Summary:</strong> {{ .CommonAnnotations.summary }}</p>
      <p><strong>Description:</strong> {{ .CommonAnnotations.description }}</p>
      <p><strong>Severity:</strong> {{ .CommonLabels.severity }}</p>
      <hr>
      <p><small>AlertManager - Smart Ape Trading Bot</small></p>

- name: 'warning-alerts'
  email_configs:
  - to: 'alerts@yourdomain.com'
    send_resolved: true
    headers:
      subject: '⚠️ WARNING: {{ .GroupLabels.alertname }}'
    html: |
      <h2>Warning Alert</h2>
      <p><strong>Alert:</strong> {{ .GroupLabels.alertname }}</p>
      <p><strong>Service:</strong> {{ .GroupLabels.service }}</p>
      <p><strong>Summary:</strong> {{ .CommonAnnotations.summary }}</p>
      <p><strong>Description:</strong> {{ .CommonAnnotations.description }}</p>
      <p><strong>Severity:</strong> {{ .CommonLabels.severity }}</p>
      <hr>
      <p><small>AlertManager - Smart Ape Trading Bot</small></p> 