# SMART APE NEURAL SWARM - MONITORING CONFIGURATION
# ===============================================

global:
  scrape_interval: 15s      # Default scrape interval
  evaluation_interval: 15s   # Default alert evaluation interval
  scrape_timeout: 10s       # Default scrape timeout
  external_labels:
    environment: production
    region: us-east-1

# Load alert rules
rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

# Scrape configurations
scrape_configs:
  # Trading Bot Metrics
  - job_name: "trading-bot"
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["trading-bot:8080"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: trading-bot
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: go_.*
        action: drop

  # Redis Metrics
  - job_name: "redis"
    static_configs:
      - targets: ["redis:9121"]
    metrics_path: /metrics
    scrape_interval: 30s

  # Node Exporter
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 30s
    metrics_path: /metrics

  # Prometheus Self-Monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    scrape_interval: 30s
    metrics_path: /metrics

  # Grafana
  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]
    scrape_interval: 30s
    metrics_path: /metrics

# Alerting configuration
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
          - "alertmanager:9093"
      timeout: 10s
      api_version: v2

# Remote write configuration (optional)
remote_write:
  - url: "http://remote-storage:9201/write"
    remote_timeout: 30s
    queue_config:
      capacity: 10000
      max_shards: 200
      max_samples_per_send: 500
      batch_send_deadline: 5s
    write_relabel_configs:
      - source_labels: [__name__]
        regex: go_.*
        action: drop

# Remote read configuration (optional)
remote_read:
  - url: "http://remote-storage:9201/read"
    read_recent: true
    remote_timeout: 30s
