# DOCKER COMPOSE - DEVELOPMENT/SIMULATION MODE
# ===========================================
# Simplified setup for testing and development

version: '3.8'

services:
  trading-bot:
    build: 
      context: .
      args:
        TRADING_MODE: simulation
        BUILD_ENV: development
    image: smart-ape-bot:dev
    container_name: smart-ape-dev
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
      - TRADING_MODE=simulation
      - ENVIRONMENT=development
    ports:
      - "8080:8080"
    volumes:
      - ./.env.production:/app/.env.production:ro
      - ./env.template:/app/env.template:ro
      - ./data:/app/data
      - ./logs:/app/logs
      - .:/app:ro  # Mount source code for development
    restart: "no"  # Don't restart automatically in dev mode
    depends_on:
      - redis
            command: ["python", "entry_points/run_bot.py", "--mode", "simulation"]

  redis:
    image: redis:alpine
    container_name: smart-ape-redis-dev
    ports:
      - "6379:6379"
    restart: "no"

  # Minimal monitoring for development
  prometheus:
    image: prom/prometheus:latest
    container_name: smart-ape-prometheus-dev
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: "no"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'

networks:
  default:
    name: smart-ape-dev-network 