version: '3.8'

services:
  # Simplified Trading Bot
  simplified-bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TRADING_MODE: ${TRADING_MODE:-production}
    container_name: simplified-trading-bot
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - TRADING_MODE=${TRADING_MODE:-production}
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.env.production:/app/.env.production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Redis for session storage (optional)
  redis:
    image: redis:7-alpine
    container_name: simplified-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped
    profiles:
      - with-redis  # Only start with --profile with-redis

volumes:
  redis_data: 