# Queen Ant Configuration
# Controls the overall colony behavior and resource allocation

# Colony Management
colony:
  initial_capital: 10.0
  min_princess_capital: 5.0
  max_workers_per_vps: 5
  max_workers: 10  # Maximum number of worker ants
  min_workers: 3   # Minimum number of worker ants
  worker_timeout: 300  # Seconds to wait before considering a worker dead
  health_check_interval: 60  # Seconds between health checks

# Capital Management
capital:
  savings_ratio: 0.2
  worker_allocation_ratio: 0.1
  princess_allocation_ratio: 0.4

# Resource Management
resources:
  initial_capital: 1000.0  # Initial capital in SOL
  max_capital_per_worker: 100.0  # Maximum capital per worker
  min_capital_per_worker: 10.0   # Minimum capital per worker
  emergency_reserve: 100.0  # Emergency reserve in SOL

# Trading Parameters
trading:
  max_concurrent_trades: 5  # Maximum number of concurrent trades
  min_profit_threshold: 0.01  # Minimum profit threshold (1%)
  max_slippage: 0.02  # Maximum allowed slippage (2%)
  max_trade_size: 1.0  # Maximum trade size in SOL
  min_liquidity: 1000.0  # Minimum liquidity requirement

# DEX Preferences
dex:
  preferred_dexes:
    - jupiter
    - orca
    - raydium
  min_dex_volume: 10000.0  # Minimum 24h volume in SOL
  max_price_impact: 0.01  # Maximum price impact (1%)

# Risk Management
risk:
  max_daily_loss: 50.0  # Maximum daily loss in SOL
  max_position_size: 200.0  # Maximum position size in SOL
  stop_loss_percentage: 0.05  # Stop loss percentage (5%)
  take_profit_percentage: 0.15  # Take profit percentage (15%)

# Monitoring
monitoring:
  log_level: "INFO"  # Log level (DEBUG, INFO, WARNING, ERROR)
  metrics_interval: 300  # Seconds between metrics collection
  alert_threshold: 0.1  # Alert threshold for significant events

# Network
network:
  rpc_url: "https://api.mainnet-beta.solana.com"
  ws_url: "wss://api.mainnet-beta.solana.com"
  commitment: "confirmed"
  timeout: 30  # Seconds

# Security
security:
  max_failed_attempts: 3  # Maximum failed attempts before blocking
  block_duration: 3600  # Block duration in seconds
  require_confirmation: true  # Require confirmation for large trades
  confirmation_threshold: 50.0  # Threshold for trade confirmation in SOL 