# AntBot Unified Configuration

# Colony Management
colony:
  initial_capital: 10.0  # Initial capital in SOL
  min_princess_capital: 5.0  # Minimum capital required to spawn a princess
  max_workers: 10  # Maximum number of worker ants
  min_workers: 3   # Minimum number of worker ants
  worker_timeout: 300  # Seconds to wait before considering a worker dead
  health_check_interval: 60  # Seconds between health checks

# Capital Management
capital:
  savings_ratio: 0.90  # Percentage of profits to save (90%)
  reinvestment_ratio: 0.80  # Percentage of savings to reinvest (80%)
  compound_frequency: 24  # Hours between compound events
  min_savings: 1.0  # Minimum SOL in savings
  max_withdrawal: 0.5  # Maximum percentage to withdraw at once
  emergency_reserve: 100.0  # Emergency reserve in SOL

# Worker Configuration
worker:
  max_trades_per_hour: 10
  min_profit_threshold: 0.01  # Minimum profit threshold (1%)
  max_slippage: 0.02  # Maximum allowed slippage (2%)
  max_trade_size: 1.0  # Maximum trade size in SOL
  min_liquidity: 1000.0  # Minimum liquidity requirement
  max_hold_time: 30  # Maximum hold time in seconds
  target_trades_per_minute: 60
  max_concurrent_trades: 5

# Risk Management
risk:
  max_position_size: 0.1  # Maximum position size as fraction of capital
  stop_loss: 0.05  # Stop loss percentage (5%)
  trailing_stop: 0.02  # Trailing stop percentage (2%)
  max_daily_loss: 50.0  # Maximum daily loss in SOL
  take_profit_percentage: 0.15  # Take profit percentage (15%)

# Network Settings
network:
  rpc_endpoint: "https://api.mainnet-beta.solana.com"
  ws_endpoint: "wss://api.mainnet-beta.solana.com"
  commitment: "confirmed"
  timeout: 30  # Seconds

# DEX Preferences
dex:
  preferred_dexes:
    - jupiter
    - orca
    - raydium
  min_dex_volume: 10000.0  # Minimum 24h volume in SOL
  max_price_impact: 0.01  # Maximum price impact (1%)

# Monitoring and Logging
monitoring:
  log_level: "INFO"
  log_rotation: "1 day"
  log_retention: "7 days"
  health_check_interval: 60  # seconds
  performance_report_interval: 300  # seconds
  alert_threshold: 0.20  # Alert if performance drops by 20%
  metrics_interval: 300  # Seconds between metrics collection 

# Worker Distribution Configuration
worker_distribution:
  max_workers_per_vps: 5  # Maximum number of workers per VPS instance
  min_vps_instances: 1  # Minimum number of VPS instances
  max_vps_instances: 10  # Maximum number of VPS instances
  cpu_threshold: 80.0  # CPU usage threshold percentage for rebalancing
  memory_threshold: 80.0  # Memory usage threshold percentage for rebalancing
  auto_scaling: true  # Automatically scale VPS instances
  load_balancing_interval: 300  # Seconds between load balancing operations
  distribution_strategy: "performance"  # Options: "even", "performance", "cost-optimized"
  preferred_regions:  # Preferred regions for VPS instances (in order)
    - "us-east"
    - "eu-west"
    - "ap-southeast"
  failover_enabled: true  # Enable failover for workers between VPS instances

# Load Balancer Configuration
load_balancer:
  enabled: true  # Enable load balancing
  check_interval: 60  # Seconds between health checks
  health_check_path: "/health"  # Health check endpoint path
  max_retries: 3  # Maximum number of retries before marking a VPS as unhealthy
  retry_delay: 5  # Seconds to wait between retries
  stickiness: true  # Enable sticky sessions
  distribution_method: "least-connections"  # Options: "round-robin", "least-connections", "ip-hash", "weighted"
  strategy_update_interval: 300  # Seconds between strategy updates

# Failover Configuration
failover:
  enabled: true  # Enable failover
  check_interval: 60  # Seconds between health checks
  max_retries: 3  # Maximum number of retries before initiating failover
  retry_delay: 5  # Seconds to wait between retries
  failback_delay: 300  # Seconds to wait before failing back to primary
  auto_restart: true  # Automatically restart failed workers
  health_check_timeout: 10  # Seconds to wait for health check response
  notification_enabled: true  # Enable notifications for failover events
  emergency_shutdown_threshold: 10  # Number of failed workers that triggers emergency shutdown
  state_sync_interval: 60  # Seconds between state synchronization

# VPS Provisioning
vps_provisioning:
  provider: "aws"  # Cloud provider (aws, gcp, azure)
  instance_type: "t3.medium"  # Default instance type
  disk_size: 20  # Disk size in GB
  regions:  # Available regions
    - name: "us-east-1"
      instance_type: "t3.medium"
      cost_per_hour: 0.0416
    - name: "eu-west-1"
      instance_type: "t3.medium"
      cost_per_hour: 0.0452
    - name: "ap-southeast-1"
      instance_type: "t3.medium"
      cost_per_hour: 0.0472
  auto_provision: true  # Automatically provision new VPS instances
  provision_threshold: 80  # Provision new instance when utilization reaches this percentage
  deprovision_threshold: 20  # Deprovision instance when utilization falls below this percentage
  max_instances_per_region: 5  # Maximum number of instances per region 