global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rule files
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter for host metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # AntBot Queen metrics
  - job_name: 'antbot-queen'
    scrape_interval: 10s
    static_configs:
      - targets: ['queen:8500']
        labels:
          instance: 'queen'
          service: 'antbot'
    
  # AntBot Workers
  - job_name: 'antbot-workers'
    scrape_interval: 10s
    static_configs:
      - targets:
        - 'worker-1:8501'
        - 'worker-2:8502'
        labels:
          service: 'antbot'

  # AntBot Dashboard
  - job_name: 'antbot-dashboard'
    scrape_interval: 30s
    static_configs:
      - targets: ['dashboard:8503']
        labels:
          instance: 'dashboard'
          service: 'antbot' 